---
title: "Progetto Elaborazione Scienza Dati"
subtitle: "di Ashean Abeysinghe"
output:
  html_document:
    theme: readable
---


**Il cibo climatico** nel seguente progetto procederemo con l'analisi di dati raccolti sul consumo di carne,
l'inquinamento e la sanità, quanto quel che mangiamo affligge la nostra salute e quella del nostro pianeta? 

**I dataset usati:**

1. "[FAO-Dataset](https://www.kaggle.com/dorbicycle/world-foodfeed-production)", 
2. "[Worldwide consumption of different meats by country from 1991](https://www.kaggle.com/vagifa/meatconsumption)",
3. "[Greenhouse gas emissions](https://github.com/owid/co2-data/blob/master/owid-co2-data.csv)". 

**Domande iniziali**
Partiamo con un paio di domande semplici:

  1. quanta carne mangiamo nelle varie nazioni?
  (grafico nazioni x consumo di carne)
  
  2. Quando abbiamo cominciato a mangiare questa quantità di carne?
  (grafito crescita consumi in occidente)
  
  3. I paesi del terzo mondo hanno incominciato più tardi a consumare carne, coincide con la crescita economica del        paese?
  
  4. Quali sono i paesi con maggiori emissioni, quante di queste emisisoni sono dovuti agli allevamenti?
  
  5. Quali sono i paesi con maggiori problemi di obesità ed con più decessi per colestorolo alto?
  
  6. Quanto costano alle varie nazioni?
  
  
  
  

Studiamo i consumi delle seguenti carni .

[SQLite](https://www.sqlite.org/index.html) is a C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine. SQLite it a good choice for data analysis:

>People who understand SQL can employ the sqlite3 command-line shell (or various third-party SQLite access programs) to analyze large datasets. Raw data can be imported from CSV files, then that data can be sliced and diced to generate a myriad of summary reports. More complex analysis can be done using simple scripts written in Tcl or Python (both of which come with SQLite built-in) or in R or other languages using readily available adaptors. (...) The same thing can be done with an enterprise client/server database, of course. The advantage of SQLite is that it is easier to install and use and the resulting database is a single file that can be written to a USB memory stick or emailed to a colleague.
